name: CI/CD for boilerplate

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: dev
      PORT: 3000
      DB_HOST: localhost
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: db_boilerplate
      JWT_SECRET: dfdhhf8gh523reh6qedn37dferpoaw@1904#
      JWT_EXPIRATION: 15m

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up node js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependency
        run: npm install

      - name: Create build
        run: npm run build

  create_release_draft:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          tag_name: v1.0.$GITHUB_RUN_NUMBER
          draft: true
          title: Release v1.0.$GITHUB_RUN_NUMBER
          body: |
            Describe your release here

      - name: Debug Draft Release
        run: |
          echo "Draft Release ID: ${{ steps.create_release.outputs.id }}"
          echo "Draft Release HTML URL: ${{ steps.create_release.outputs.html_url }}"

  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Set GHE_HOST
        run: |
          echo "GHE_HOST=${GITHUB_SERVER_URL##https:\/\/}" >> $GITHUB_ENV

      - name: Release Drafter
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
