name: Deploy Draft Release on Production

on:
  release:
    types: [published]

jobs:
  deploy:
    if: github.event.release.draft == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: SSH into server and checkout main branch
        uses: appleboy/ssh-action@master
        with:
          host: 34.239.108.195
          username: ubuntu
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/my-app/
            git checkout main
