name: Deploy Draft Release on Production

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Current path
        run: pwd

      - name: copy file via ssh key
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 54.210.4.139
          username: ubuntu
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "*"
          target: /var/www/my-app/