name: Deploy Draft Release on Production

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Current path
        run: pwd        

      # - name: Set up SSH key
      #   uses: webfactory/ssh-agent@v0.5.4
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # - name: rsync deployments
      #   uses: burnett01/rsync-deployments@6.0.0
      #   with:
      #     switches: -avzr --delete
      #     path: ./
      #     remote_path: /var/www/my-app/
      #     remote_host: 34.239.108.195
      #     remote_user: ubuntu
      #     remote_key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync

      - name: Deploy folders to remote server
        run: |
              pwd
              ls -la
              rsync -avz --delete --ignore-times -e "ssh -o StrictHostKeyChecking=no" ${{ github.workspace }}/home/runner/work/node-ts-boilerplate/node-ts-boilerplate ubuntu@34.239.108.195:/var/www/my-app/
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}


      # - name: SSH into server and checkout main branch
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: 34.239.108.195
      #     username: ubuntu
      #     key: ${{ secrets.SERVER_SSH_KEY }}
      #     script: |
      #       cd /var/www/my-app/
      #       git checkout main
