name: Deploy Draft Release on Production

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Current path
        run: pwd

      - name: copy file via ssh key
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 34.239.108.195
          username: ubuntu
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "*"
          target: /var/www/my-app/

      # - name: copy file via ssh on server 2
      #   uses: appleboy/scp-action@v0.1.7
      #   with:
      #     host: 159.69.198.110
      #     username: root
      #     password: cicd1904
      #     source: "*"
      #     target: /home/my-app/

      - name: SSH into server and checkout main branch
        uses: appleboy/ssh-action@master
        with:
          host: 34.239.108.195
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/my-app/
            npm run build