name: Deploy Draft Release on Production

on:
  release:
    types: [published]

jobs:
  deploy:
    if: github.event.release.draft == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download release assets
        id: download_release_assets
        uses: actions/download-artifact@v2
        with:
          name: release-assets
          path: ./disct/*

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Deploy to server
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./release-assets/*
          remote_path: /var/www/my-app/
          remote_host: 34.239.108.195
          remote_user: ubuntu
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
