name: Stage Release

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy_on_stag_server:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'

    steps:
      - uses: actions/checkout@v3

      - name: Loop through servers and deploy
        run: |
          IFS=$'\n' # Set the Internal Field Separator to newline
          for server_config in ${{ secrets.SERVER_LIST }}; do
            # Extract server configuration values
            host=$(echo $server_config | cut -d',' -f1)
            username=$(echo $server_config | cut -d',' -f2)
            password=$(echo $server_config | cut -d',' -f3)
            working_dir=$(echo $server_config | cut -d',' -f4)
            
            echo "Deploying to $host"
            
            # Copy files via SCP
            echo "Copying files to $host"
            scp -r * $username@$host:$working_dir
            
            # SSH to server and run commands
            echo "Running commands on $host"
            sshpass -p $password ssh $username@$host << EOF
              cd $working_dir
              which npm
              npm install --production
              npm run lint .
            EOF
          done
        env:
          SSH_AUTH_SOCK: /tmp/ssh_auth_sock
        shell: bash
