name: Stage Release

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy_on_stag_server:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'

    steps:
      - uses: actions/checkout@v3

      - name: Copy files via SSH on Server 1
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 52.87.241.125
          username: ubuntu
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "*"
          target: ${{ secrets.APP_DIR }}

      - name: SSH to Server and run commands
        uses: appleboy/ssh-action@master
        with:
          host: 52.87.241.125
          username: ubuntu
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.APP_DIR }}
            NPM_PATH=$(which npm)
            PM2_PATH=$(which pm2)
            $NPM_PATH install --production
            $NPM_PATH run lint .
            $PM2_PATH restart API