name: Stage Release

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy_on_stag_server:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'

    steps:
      - uses: actions/checkout@v3

      - name: Copy files via SSH on Server 1
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 54.167.213.253
          username: ubuntu
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "*"
          target: /var/www/html/
      
      - name: Get Node.js binary path
        run: echo "::set-output name=node_path::$(which npm)"

      - name: SSH to Server and run commands
        uses: appleboy/ssh-action@master
        with:
          host: 54.167.213.253
          username: ubuntu
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html/
            which npm
            export PATH="$PATH:$(which npm)"
            npm install